# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on:
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: stantest
          MYSQL_USER: stan
          MYSQL_PASSWORD: stanpw

    steps:
    - name: start mysql
      run: |
        sudo /etc/init.d/mysql start
    - name: wait for service
        uses: jakejarvis/wait-action@v0.1.0
        with:
          time: '10s'
    - name: verify mysql from container
      run: |
        mysql -h localhost -P 3306 -uroot -e "SHOW DATABASES" 
    - uses: actions/checkout@v2
    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package --file pom.xml
