# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on:
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      mydb:
        image: mysql:8.0.1
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: stantest
          MYSQL_USER: "stan"
          MYSQL_PASSWORD: "stanpw"
          ports: 3306

    steps:
    - name: verify mysql from container
      run: |
        apt-get update
        apt-get install -y mysql-client
        mysql --host mydb -uroot -p -e "SHOW DATABASES" 
    - uses: actions/checkout@v2
    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package --file pom.xml
